#! /bin/sh -e

source /usr/share/debconf/confmodule

db_input medium ltsp-core/ltsp_initialize || true
db_go
if test -e /tftpboot/lts/ltsroot -o -e /usr/lib/lts/ltsroot; then
    db_input medium ltsp-core/upgrade_location || true
    db_go
fi
