#!/bin/bash

if test -z $1; then
  echo You have to specify a language, i.e. "./builddocs fr".
  exit
fi

LANG=$1

DIR=`pwd`
cd `dirname $0`

cd ../src
latex userguide.$LANG.tex
latex userguide.$LANG.tex
dvips -t a4 userguide.$LANG.tex -o userguide.$LANG.ps
ps2pdf userguide.$LANG.ps

mv userguide.$LANG.dvi ../out
mv userguide.$LANG.ps ../out
mv userguide.$LANG.pdf ../out

cd $DIR
