#! /bin/sh

# Script to extract the available options from a LTSP installation and
# from the webmin module.
# Useful to check wether the module has all options.
# Note that not all options can not be extracted from rc.local
# correctly, because their names are constructed from variables, such as
# MODULE_${i}. But you see the point.
#
# If you set DEBUG=1 in ltsp/globals.pl, ltsp/ltsp-lib.pl will check the
# consistency of the options in ltsp/options/ and the file ltsp/options/order.
# This should be done before every release.
#
# Copyright 2001 Georg Baum <gbaum@users.sourceforge.net>

(
cd `dirname $0`

# Adjust this if needed
LTSROOT=/tftpboot/lts/ltsroot/

# Get the LTSP version
. ${LTSROOT}/etc/version

FILES="${LTSROOT}/etc/rc.local \
       ${LTSROOT}/etc/rc.setupx \
       ${LTSROOT}/etc/rc.setupx3 \
       ${LTSROOT}/bin/set_runlevel \
       ${LTSROOT}/bin/telnet_loop \
       ${LTSROOT}/bin/start_telnet"

CAT_FILES=""
for f in ${FILES}
do
  test -f ${f} && CAT_FILES="${CAT_FILES} ${f}"
done

cat ${CAT_FILES} \
    | grep -v 'ltsbin' \
    | grep '.*`.*get.*cfg.*`.*' \
    | sed 's/.*get.*cfg[[:space:]]*\([^[:space:]]*\)[[:space:]]*.*`.*/\1/g' \
    | sort | uniq > options.${VERSION}

ls -ICVS -Iorder ltsp/options | sort | uniq > options.ltsp-webmin

#mgdiff options.${VERSION} options.ltsp-webmin
)